import { CharacterType } from "@/types/Character.type"

export const emptyCharacter: CharacterType = {
  characterID: '',
  playerID: '',
  characterName: '',
  avatarurl: '',
  advancementType: 'milestone',
  hitpointAdvance: 'fixed',
  encumbranceRule: 'standard',
  encumbranceCoins: false,
  abilityScoreDisplay: 'modifier',
  gender: 'f',
  level: 1,
  appearance: '',
  backstory: '',
  personality: '',
  alignment: 'true neutral',
  armorClass: 0,
  shield: false,
  hitpoints: {
    current: 0,
    temp: 0,
    max: 0,
    hitDice: {
      spent: 0,
      max: 0,
      sides: 6,
    },
    deathSaves: {
      successes: 0,
      failures: 0,
    },
  },
  languages: 'Common',
  equipment: '',
  coin: {
    copper: 0,
    silver: 0,
    electrum: 0,
    gold: 0,
    platinum: 0,
  },
  proficiencyBonus: 0,
  heroicInspiration: 0,
  initiative: 0,
  speed: 0,
  size: 'medium',
  passivePerception: 0,
  attributes: {
    strength: {
      modifier: 0,
      score: 0,
      savingThrow: { proficient: false, value: 0 },
      athletics: { proficient: false, value: 0 },
    },
    dexterity: {
      modifier: 0,
      score: 0,
      savingThrow: { proficient: false, value: 0 },
      acrobatics: { proficient: false, value: 0 },
      sleightOfHand: { proficient: false, value: 0 },
      stealth: { proficient: false, value: 0 },
    },
    constitution: {
      modifier: 0,
      score: 0,
      savingThrow: { proficient: false, value: 0 },
    },
    intelligence: {
      modifier: 0,
      score: 0,
      savingThrow: { proficient: false, value: 0 },
      arcane: { proficient: false, value: 0 },
      history: { proficient: false, value: 0 },
      investigation: { proficient: false, value: 0 },
      nature: { proficient: false, value: 0 },
      religion: { proficient: false, value: 0 },
    },
    wisdom: {
      modifier: 0,
      score: 0,
      savingThrow: { proficient: false, value: 0 },
      animalHandling: { proficient: false, value: 0 },
      insight: { proficient: false, value: 0 },
      medicine: { proficient: false, value: 0 },
      perception: { proficient: false, value: 0 },
      survival: { proficient: false, value: 0 },
    },
    charisma: {
      modifier: 0,
      score: 0,
      savingThrow: { proficient: false, value: 0 },
      deception: { proficient: false, value: 0 },
      intimidation: { proficient: false, value: 0 },
      performance: { proficient: false, value: 0 },
      persuasion: { proficient: false, value: 0 },
    }
  },
  spellcasting: {
    ability: 'none',
    modifier: 0,
    spellsaveDc: 0,
    attackBonus: 0,
  },
  spellSlots: {
    levelOne: { total: 0, expended: 0 },
    levelTwo: { total: 0, expended: 0 },
    levelThree: { total: 0, expended: 0 },
    levelFour: { total: 0, expended: 0 },
    levelFive: { total: 0, expended: 0 },
    levelSix: { total: 0, expended: 0 },
    levelSeven: { total: 0, expended: 0 },
    levelEight: { total: 0, expended: 0 },
    levelNine: { total: 0, expended: 0 },
  }
}